### ISSUE TITLE
Added User unable to access the Web App created from Dashboard Starter Pack

### ISSUE THREAD

**Issue by ajayksingh75** [PredixDev/predix-seed#10]
I have created a Web App using Dashboard Starter Pack. After adding the user using UAAC commands and cf push, when I go to the Web App, I am unable to log in using the User Credentials.

**Comment by srk289** [comment]
any updates on this issue?

**Comment by srk289** [comment]
?

**Comment by gstroup** [comment]
Please try again with the latest predix-seed code.  UAA is no longer required.  Closing this issue.  Thanks.
