### ISSUE TITLE
Unable to retrieve user information from Shared-UAA using the default passport strategy

### ISSUE THREAD

**Issue by akshayeshenoi** [PredixDev/predix-seed#104]
Hi,
I've configured the seed to work with Shared-UAA. Login and authentication works, but I can't seem to retrieve user information from the endpoint:
[UAA URL]/userinfo

Is there something wrong with the Passport strategy?

**Comment by gstroup** [comment]
Good question.  We do need to add a route to the predix-seed for the UAA /userinfo endpoint.  I'm not convinced it should be part of the Passport package though.  We are planning to add a /userinfo route to the predix-seed server application which will add the token, and proxy the request through to your UAA instance.

**Comment by akshayeshenoi** [comment]
Oh alright. 
To get around the problem, I just added a middleware after passport authentication that fetches the information from /userinfo by adding the access token in the header. 
It adds the details to the _request_ object which I can use later.

**Comment by gstroup** [comment]
Great, I'm glad you figured it out.  If you think your solution is good, and reusable, we would be happy to take a pull request.  :)  Thanks.

**Comment by RUjjwal** [comment]
Hi akshayeshenoi, I am also facing the same issue. If possible, can you share your middleware which you have created. I am not able to get userinfo from "/userinfo" endpoint. Thanks in advance.

**Comment by gstroup** [comment]
His middleware is available now on the "develop" branch of this repo.  Will be merged in to master branch, probably in a few weeks.  See server/routes/user-info.js
