### ISSUE TITLE
Any design templates around for predix-ui?

### ISSUE THREAD

**Issue by schaveyt** [PredixDev/predix-seed#110]
I am looking for any photoshop or visio or powerpoint templates?

**Comment by randyaskin** [comment]
We have Sketch and Illustrator stencils for Predix UI, you (as a GE employee) can access them on [design.team.ge.com/predix/platform](design.team.ge.com/predix/platform) under the blue Download Assets link.

**Comment by schaveyt** [comment]
Thx!
