### ISSUE TITLE
Why is this repo so large?

### ISSUE THREAD

**Issue by bsyk** [PredixDev/predix-seed#111]
Why is this repo so large?  Cloning it took 48 MB!
```
Receiving objects: 100% (17827/17827), 48.62 MiB
```

**Comment by gstroup** [comment]
Good question.  About 90% of those bytes are in the .git history.  (You might say this project has a long colorful history.)  We're looking at ways to reduce the size, and we've been considering moving to a new fresh "predix-ui-seed" repo anyway, which would also solve this problem.

**Comment by gstroup** [comment]
Check out the new starter app:
https://github.com/PredixDev/predix-webapp-starter

`Receiving objects: 100% (169/169), 890.46 KiB`
