### ISSUE TITLE
Changing the seed px-color from light to dark

### ISSUE THREAD

**Issue by pagadalasrikanth** [PredixDev/predix-seed#114]
Current predix seed imports px-colors-design/_settings.colors.scss in the seed-theme.scss. 
If I try to import the px-colors-design/_settings.colors-dark.scss, it throws an error 

Error: Undefined variable: "$gray9".
        on line 9 of public/seed-theme.scss
>> $px-page-html-background-color: $gray9;

As the _settings.colors-dark.scss contains "$d-gray9" instead of "$gray9" it will throw an error.
 How can we avoid this issue ?

And is there any chance that the themes can be changed on runtime ?

**Comment by gstroup** [comment]
At the moment, the seed app does not support different themes.  (As you discovered!)  This is a good idea though.  We should make the seed app "themable" i.e. supporting various themes.  Hopefully we can add this support soon.  I'll mark this as a feature request for now.  Thanks.

In the meantime, you'll have to change those lines in seed-theme.scss to use the $d- variables.

**Comment by randyaskin** [comment]
Actually, it can be themed. First run `bower install px-dark-theme`, then in _index.html, change lines 15 and 16 from px-theme to px-dark-theme. Voila! No need to mess with sass variables or px-colors-design.

**Comment by gstroup** [comment]
My mistake!  Thanks @randyaskin

**Comment by pagadalasrikanth** [comment]
@randyaskin Explored the dark theme and it worked :+1: 
What I would love to see is to change the theme from px-dark-theme to px-theme in the runtime.

**Comment by randyaskin** [comment]
I haven't tried this myself, but I know our team is working on something similar for our demo pages to switch between light and dark themes. If you're able to dynamically update the URL / style declaration, you may need to use the Polymer.updateStyles() method per https://www.polymer-project.org/1.0/docs/devguide/styling#style-api
