### ISSUE TITLE
Why restart server/app.js when javascript files changed in public folder?

### ISSUE THREAD

**Issue by jiqiang** [PredixDev/predix-seed#115]
In tasks/serve.dev.start.js, gulp-nodemon watches javascript files change in public folder and restart server/app.js. However, javascript files in public folder are used for UI (front-end) only. As restarting server/app.js doesn't trigger browser reload, the result of this action has nothing related to the front-end javascript change . Shouldn't it watch node scripts in server folder?

**Comment by gstroup** [comment]
I don't see the behavior you're describing.  The "watch.public" task only watches the public directory:
https://github.com/PredixDev/predix-seed/blob/master/tasks/watch.public.js
nodemon only restarts the server if the /server directory changes.

**Comment by jiqiang** [comment]
@gstroup thanks for your quick response!
Here are the steps to re-produce this behavior:

1. git clone --depth 1 https://github.com/predixdev/predix-seed
2. cd predix-seed
3. npm install
4. bower install
5. gulp
6. try to create or update any javascript files inside public folder (e.g touch public/elements/px-deck/test.js) and keep an eye on the console. You will see this:

![screen shot 2017-04-07 at 9 11 21 am](https://cloud.githubusercontent.com/assets/938491/24779215/3e19a51e-1b72-11e7-8f12-f3e9dc7cdeba.png)

gulp version: 3.9.1
node version: 7.8.0

'use strict';

// -------------------------------------
//   Task: Serve
// -------------------------------------
const nodemon = require('gulp-nodemon');

module.exports = function() {
  return function() {
    nodemon({
        script: 'server/app.js',
        **env: { 'base-dir' : '/../public'}**
      })
      .on('restart', function() {
        console.log('app.js restarted');
      });
  };
};

I guess the code in bold telling nodemon to watch public folder ?

**Comment by gstroup** [comment]
fixed in new version of predix-webapp-starter.
