### ISSUE TITLE
gulp not compiling SCSS file to CSS

### ISSUE THREAD

**Issue by kasuladevivijay** [PredixDev/predix-seed#116]
Hi,

gulp is not compiling the **public/index-inline.scss** file to **public/index-inline.css** file, As a result the predix-ui css styles are not being applied. In the previous versions of predix-seed it used to work and we get the compiled **index-inline.css** file. 
I have tried with predix tables css and the result is like this
![issue](https://cloud.githubusercontent.com/assets/6322307/25201906/4c3817bc-2508-11e7-8316-226ab95072ae.JPG)

**Comment by charnpreetsingh** [comment]
I'm also having this issue.

**Comment by gstroup** [comment]
Try the new starter app: https://github.com/PredixDev/predix-webapp-starter

In this app, the index-inline.scss is compiled to index-inline-styles.html.

**Comment by kasuladevivijay** [comment]
Hi @gstroup ,
It's still not working in the new version, the index-inline-styles.html are already imported in the index.html but the styles are not rendered. I tried with tables and toggle button, followed the steps as in predix-ui.com. This is what I got after implementing the styles
![screenshot 2017-05-12 10 36 40](https://cloud.githubusercontent.com/assets/6322307/25983049/6d0942dc-36ff-11e7-85ec-783647af998f.png)

**Comment by poojakedar** [comment]
I'm facing same issue. someone please provide some solution
