### ISSUE TITLE
Dependencies are horribly out of date

### ISSUE THREAD

**Issue by nonmetalhail** [PredixDev/predix-seed#117]
The Predix UI components that come packaged with the seed are horribly out of date. This leads to a dependency hell for users who try to develop off the seed. They need to be updated to current versions or at least come with instructions informing the developers they need to do this.

**Comment by gstroup** [comment]
Check out the new repo, with more recent versions of px components.
https://github.com/PredixDev/predix-webapp-starter
If you see problems, please open an issue in that repo.  Thanks.
