### ISSUE TITLE
IE 11 Issues

### ISSUE THREAD

**Issue by ugurk** [PredixDev/predix-seed#118]
It does not work properly, see screenshot:

* No footer menu
* Left menu overflow

![ie11_issue](https://cloud.githubusercontent.com/assets/642063/25840905/72bf83ea-34a6-11e7-9cae-94de1a4a8fab.png)

OS: Windows 7
Browser: IE 11

**Comment by turnerth** [comment]
Hi there, please try out https://github.com/PredixDev/predix-webapp-starter instead.
