### ISSUE TITLE
bower install is failing with error

### ISSUE THREAD

**Issue by romit7** [PredixDev/predix-seed#13]
bower requirejs#2.1.18               invalid-meta requirejs is missing "main" entry in bower.json
bower requirejs#2.1.18               invalid-meta requirejs is missing "ignore" entry in bower.json
bower requirejs#2.1.18                   resolved https://github.com/jrburke/requirejs.git#2.1.18
bower px-card#~v0.2.3                     ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/PredixDev/px-card.git", exit code of #128 github --credentials get: g
 'https://github.com': Invalid argument

Additional error details:
github --credentials get: github: command not found
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument

**Comment by nonmetalhail** [comment]
@carlosfhernandez Can you please create a rally story for this?

**Comment by mdwragg** [comment]
Fixed in 0a8c1c8c1a56a35a375c018e65d2c2a27cf251fa
