### ISSUE TITLE
when deploying predix seed application getting " ERROR: 'There is no timestamp for /base/public/bower_components/jquery/dist/jquery.min.js!'"

### ISSUE THREAD

**Issue by mamidishetti** [PredixDev/predix-seed#14]
Hi Team,

when i'm running **grunt dist** command getting fallowing  error
--------------------------------------------------------------
D:\GEGDC\MD98012\predixSeedAPP\Dashboard_Starter_Pack_directory\predix-seed-develop>grunt dist
Running "clean:build" (clean) task

Running "jshint:src" (jshint) task
>> 22 files lint free.

Running "jshint:test" (jshint) task
>> 6 files lint free.

Running "jshint:src" (jshint) task
>> 22 files lint free.

Running "jshint:test" (jshint) task
>> 6 files lint free.

Running "clean:test" (clean) task
Cleaning test-target/...OK

Running "karma:runner" (karma) task
WARN [watcher]: Pattern "D:/GEGDC/MD98012/predixSeedAPP/Dashboard_Starter_Pack_directory/predix-seed-develop/public/bower_components/**/*.js
" does not match any file.
public/views/blank-sub-page.html
public/views/dashboards.html
public/views/blank-page.html
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Windows 7 0.0.0)]: Connected on socket q5TzMvM4ZsLZyaUClpqy with id 78961779
WARN [web-server]: 404: /base/public/bower_components/jquery/dist/jquery.min.js
PhantomJS 1.9.8 (Windows 7 0.0.0) ERROR: 'There is no timestamp for /base/public/bower_components/jquery/dist/jquery.min.js!'

PhantomJS 1.9.8 (Windows 7 0.0.0) ERROR
  Error: Script error for "jquery"
  http://requirejs.org/docs/errors.html#scripterror
  at D:/GEGDC/MD98012/predixSeedAPP/Dashboard_Starter_Pack_directory/predix-seed-develop/public/scripts/config.js:9

Warning: Task "karma:runner" failed. Use --force to continue.

Aborted due to warnings.
--------------------------------------------
--------------------------------------------

Please help me in fixing the issue

Thanks
Divya.M

**Comment by shahid1ansari** [comment]
my grunt dist is also failing its straight away getting aborted. what resolution you got for your problem

**Comment by gstroup** [comment]
Looks like Jquery is missing for some reason.  Did you run `bower install`?  Did it succeed?  Try running it again, then `grunt dist`.

**Comment by nonmetalhail** [comment]
@carlosfhernandez Can you please create a rally story for this?

**Comment by mdwragg** [comment]
jQuery (and Angular) is now dropped from the latest seed so will close this...
