### ISSUE TITLE
json-proxy causes issues with certain proxy servers

### ISSUE THREAD

**Issue by mrkb80** [PredixDev/predix-seed#23]
When deploying the predix-seed app locally, the json-proxy library can cause issues interacting with certain proxy servers (particularly some GE proxy servers) which prevents the correct redirect rules from applying.  I HIGHLY recommend you switch to http-proxy-middleware library as it a) fixes these issues with GE b) will likely prevent others from having problems.

I have documented the changes that you need to apply to here: https://forum.predix.io/questions/3268/local-deploy-of-seed-app.html

**Comment by gstroup** [comment]
We definitely need to fix this issue.  (This is the same as issue #9 .)  Seed app just doesn't work on GE network, without changes to the proxy.
Mark - would you be able to make a pull request with this fix?  If not, I will try to find the time to do it.
Thanks.
