### ISSUE TITLE
MacOSX Issue with PhantomJS launcher (with Fix)

### ISSUE THREAD

**Issue by futur** [PredixDev/predix-seed#25]
I faced an error and it is resolved with an additional step, Just thought of sharing this with the community. When I executed

`grunt dist`

I faced the following error in the karma execution sequence.

`Running "clean:build" (clean) task

Running "jshint:src" (jshint) task
>> 22 files lint free.

Running "jshint:test" (jshint) task
>> 6 files lint free.

Running "jshint:src" (jshint) task
>> 22 files lint free.

Running "jshint:test" (jshint) task
>> 6 files lint free.

Running "clean:test" (clean) task
Cleaning test-target/...OK

Running "karma:runner" (karma) task
public/views/blank-page.html
public/views/blank-sub-page.html
public/views/dashboards.html
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
ERROR [launcher]: No binary for PhantomJS browser on your platform.
  **Please, set "PHANTOMJS_BIN" env variable.**`

To fix this, we have to run 
`npm install karma-phantomjs-launcher --save`

But this package is included in package.json but still it doesn't pick up from there, so once the above command is complete run the following.  

export "PHANTOMJS_BIN=`` `which phantomjs` ``" 

and 

`npm install` again. This will solve this problem.

**Comment by nonmetalhail** [comment]
@carlosfhernandez Can you please create a rally story for this? Sounds like we should capture it in our documentation

**Comment by mdwragg** [comment]
Fixed by 0a8c1c8c1a56a35a375c018e65d2c2a27cf251fa - we've moved away from grunt & karma in favour of gulp & WCT.

**Comment by LotharSchubert** [comment]
Great thanks.
