### ISSUE TITLE
Grunt Dist Fails 

### ISSUE THREAD

**Issue by Training-Predix** [PredixDev/predix-seed#26]
Running "vulcanize:dist" (vulcanize) task
ERROR finding /Users/212427954/code/githubcom/predixDev/predix-seed/public/bower_components/px-sample-cards/bower_components/d3/d3.js
Fatal error: ENOENT: no such file or directory, open '/Users/212427954/code/githubcom/predixDev/predix-seed/public/bower_components/px-sample-cards/bower_components/d3/d3.js'

**Comment by mdwragg** [comment]
@gstroup - this is the same issue you referred to [here] (https://github.com/Polymer/vulcanize/issues/297), how did you fix the issue you were having?

cc/ @ek @runn-vermel

**Comment by bbayo4** [comment]
I have the same issue... I try to do npm shrinkwrap but that did not solve the problem. Any solution for this issue.

**Comment by mdwragg** [comment]
Fixed by a734a01

**Comment by mdwragg** [comment]
`shrinkwrap` solution works if you are using npm 3.x. This wont work in npm 2.x versions...
