### ISSUE TITLE
Error: tunneling socket could not be established, cause=read ECONNRESET

### ISSUE THREAD

**Issue by jimkd1yv** [PredixDev/predix-seed#31]
N00b here, trying to install predix-seed as a demo.  Consistently getting error mentioned in subject.

Running on OSX Yosemite 10.10.5.  Searching this error, I tried a couple of variants on proxy settings as environment variables, as well as npm config set proxy.  Results still the same.  I also installed connect.js as mentioned here https://forum.predix.io/questions/3268/local-deploy-of-seed-app.html and also proxy.js as mentioned here https://github.com/PredixDev/rmd-ref-app-ui/blob/master/tasks/helpers/proxy.js .

Attached is the whole console log from npm install, as well as the debug log
[2github.zip](https://github.com/PredixDev/predix-seed/files/215751/2github.zip)

**Comment by nonmetalhail** [comment]
@carlosfhernandez Can you please create a rally story for this?

**Comment by mdwragg** [comment]
Fixed in 0a8c1c8c1a56a35a375c018e65d2c2a27cf251fa
