### ISSUE TITLE
px navbar mainElement is not defined

### ISSUE THREAD

**Issue by alaviamir** [PredixDev/predix-seed#32]
I encounter a javascript reference error when switching between nav items in the px-app-nav list.

Here is the where the issue is occurring:
polymer-loader.vulcanized.html:14951 Uncaught ReferenceError: mainElement is not defined

It appears that mainElement has not been defined at this point in time.

Please let me know if you've encountered this before and whether you have a fix/workaround for it!

**Comment by nonmetalhail** [comment]
@carlosfhernandez Can you please create a rally story for this?

**Comment by alaviamir** [comment]
I changed the version of px-app-nav to the latest in bower.json and it fixed my issue

**Comment by nonmetalhail** [comment]
Great. Glad to hear it. Thanks for following up.
