### ISSUE TITLE
Step 2 of View configuration example is probably wrong and misleading

### ISSUE THREAD

**Issue by ggleizer** [PredixDev/predix-seed#33]
Here is the text in the readme:

> ### Step 2. Update View service reference in nginx.conf
> 
> You need to update nginx.conf (in the dist folder) wherever it has references to predix_seed_view_service to the name of your_view_service_instance, which is whatever you specified in step 1. 
> 
> ```
> # for example, from
> proxy_set_header    predix-zone-id   "<%= ENV["vcap_service_predix_seed_view_service_instanceId"] %>";
> proxy_pass  "<%= ENV["vcap_service_predix_seed_view_service_uri"] %>";
> 
> # to (assuming you changed your_view_service_instance to my_special_views_service in your manifest.yml)
> proxy_set_header    predix-zone-id   "<%= ENV["vcap_service_my_special_views_service_instanceId"] %>";
> proxy_pass  "<%= ENV["vcap_service_my_special_views_service_uri"] %>";
> ```
> 

I think that, in the example, the name of the instance is your_view_service? (Instead of your_view_service_instance)

Thanks,
Gabriel.

**Comment by gstroup** [comment]
Closing, since the seed app now uses Express, not nginx.
