### ISSUE TITLE
Where to find the Dashboard Seeds' project Sass file?

### ISSUE THREAD

**Issue by Aanchal25** [PredixDev/predix-seed#34]
I need to import the "@import "px-buttons-design/_objects.buttons.scss" but not getting the project sass file.

**Comment by nonmetalhail** [comment]
You can see an example in our other repos such as this one:
https://github.com/PredixDev/px-modal/blob/master/sass/px-modal-sketch.scss

The imports are grouped by hierarchy following the inuit css model:
1) Generic
2) Base
3) Objects
4) Component
5) Trumps

Make sure you also set the boolean flags for the styles you want before the import. For example: 

```
$inuit-enable-btn--primary      : true;
@import "px-buttons-design/_objects.buttons.scss";

```
See the design repo for the variables to enable the styles you want.
