### ISSUE TITLE
grunt dist is failing with the Error: EMFILE, too many open files

### ISSUE THREAD

**Issue by ericfulkerson** [PredixDev/predix-seed#37]
When I was building a project I ran across this error in the Karma package. It can be fixed by updating the version of Karma to ~0.13.0 and Grunt-Karma to ~1.0.0

**Comment by mdwragg** [comment]
Fixed by 0a8c1c8c1a56a35a375c018e65d2c2a27cf251fa - we've moved away from both Grunt and karma in favour of gulp and WCT.

**Comment by LotharSchubert** [comment]
Great thanks.
