### ISSUE TITLE
Dashboard Seed not working - card, widget, deck

### ISSUE THREAD

**Issue by p021918** [PredixDev/predix-seed#41]
Overview screen (displaying card, widget, deck etc) of Dashboard Seed app on predix.io site is not working for several weeks.
We often use this app for customer demo. I have opened a ticket to support team, but in case of any code change impact on this, please advise. thanks

 https://www.predix.io/services/starter-pack.html?id=1225 

https://predix-seed.run.aws-usw02-pr.ice.predix.io/dashboards

**Comment by gedesigntech** [comment]
Hello, thanks for reaching out and sorry for the delayed response.  Alot has happened with the development of the seed, and we have just released a major new version at the start of this month.  Please see the 'master' and 'develop' branches for the new version.  The demo of this new version can be seen at:

https://predix-ui-seed.run.aws-usw02-pr.ice.predix.io/

The previous version (in the URL you cited above) is still available, though not linked from predix.io anymore, and maybe taken down anytime.

**Comment by gedesigntech** [comment]
New version of seed will continue to be developed and maintained.  Older Dashboard Seed no longer developed and supported, but documentation still available.
