### ISSUE TITLE
grunt-bump causes npm install to fail

### ISSUE THREAD

**Issue by john-k-ge** [PredixDev/predix-seed#45]
Currently, the package.json stipulates grunt-bump version 0.8.0.  Unfortunately, this version of grunt-bump requires grunt version >= 1.0.1.  npm install works fine if grunt-bump is downgraded to 0.7.0 (which only relies upon grunt 0.4.0).

**Comment by mdwragg** [comment]
Fixed in 0a8c1c8c1a56a35a375c018e65d2c2a27cf251fa
