### ISSUE TITLE
npm install fails on branch 'polymer-only' due to Grunt version dependencies

### ISSUE THREAD

**Issue by murone** [PredixDev/predix-seed#47]
Fails with following error: 

npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package grunt@0.4.5 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-contrib-requirejs@0.4.4 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-includes@1.0.0 wants grunt@>=1.0.0
npm ERR! peerinvalid Peer grunt-insert@0.1.0 wants grunt@~0.4.1
npm ERR! peerinvalid Peer grunt-karma@0.8.3 wants grunt@0.4.x
npm ERR! peerinvalid Peer grunt-contrib-clean@0.5.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-sass@1.2.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-config@0.2.2 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-autoprefixer@3.0.4 wants grunt@>=0.4.2
npm ERR! peerinvalid Peer grunt-contrib-copy@0.8.2 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-watch@0.6.1 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-jshint@0.8.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer load-grunt-tasks@3.5.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-connect@0.7.1 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-concurrent@2.3.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-cssmin@0.12.3 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-nodemon@0.4.2 wants grunt@>=0.4.0

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\210071205\version-control\predix\px\predix-seed\npm-debug.log

npm-debug attached.
[npm-debug.log.txt](https://github.com/PredixDev/predix-seed/files/391551/npm-debug.log.txt)

**Comment by srk289** [comment]
same issue here

**Comment by murone** [comment]
Looks like it requires npm3.x, which is a shame because that causes conflicts in other places. 
https://forum.predix.io/questions/10024/predix-seed-npm-install-error-peerinvalid.html

**Comment by ek** [comment]
Hi @murone & @srk289 

Good news: Grunt is being phased out of our development toolchain and we are migrating to Gulp so this should be resolved very soon! I'll follow up on this thread when completed.

**Comment by srk289** [comment]
@ek Thats awesome. I remember you talking about migrating to Gulp in our meeting in Vegas 👍

**Comment by murone** [comment]
Was going to close because a new version of NPM fixes this, but on second thought I'll leave it open until @ek confirms the move to gulp.

**Comment by Charlesjwilliams2** [comment]
The README.md needs to be updated to remove references to grunt and add gulp notes.

**Comment by gstroup** [comment]
Yes, please use gulp in polymer-only branch.  README also has been updated.
