### ISSUE TITLE
Polymer-only and protected routes

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/predix-seed#48]
I love the direction this project is headed w/ lots of Polymer and Gulp as the build tool. 
However, I do not understand how the authentication flow is supposed to work. The _changes-to-seed.txt_ talks about _ensureLogin_ but I do not see that implemented anywhere. Also there's no nginx which does most of the oauth heavy-lifting on develop/master. Can somebody shed some light onto this?

**Comment by gedesigntech** [comment]
Thanks, @davidsteinberger for your questions and comments.  We are re-releasing the project as a Polymer implementation in the near future, likely within the month.  This initial Polymer-ized release will have the essential examples for navigation, routing, tests etc.  We have taken out authentication and NGINX integration to keep things simple, easily set up, and with emphasis on the frontend.  At the same time, such release will have code that is supportive of authentication, NGINX integration and other enhancements that adopters may want to add.

**Comment by gedesigntech** [comment]
New version of the seed released on Oct 6.  Upcoming release (most likely mid-December) will contain tutorial and sample code for authentication integration.
