### ISSUE TITLE
Polymer-only Branch: Gulp Doesn't Watch

### ISSUE THREAD

**Issue by srk289** [PredixDev/predix-seed#50]
Gulp watch task isn't watching for changes in SCSS or HTML. The changes made are in effect only after we rerun gulp.

**Comment by gedesigntech** [comment]
Fixed, thanks for raising this.

Commit info: 
https://github.com/PredixDev/predix-seed/commit/99bf18dad1dbb1dfbcb6ab9f04203c6df18b9be6
