### ISSUE TITLE
Polymer Only: px-rangepicker doesn't render correctly (icons are massive)

### ISSUE THREAD

**Issue by manderson23** [PredixDev/predix-seed#54]
In the polymer only seed I replaced the blank-card element with the following px-rangepicker component

``` 
<px-rangepicker range='{"from":"2016-01-01T00:00:00.000Z","to":"2016-07-01T11:00:00.000Z"}'></px-rangepicker>
```
In the polymer only seed it doesn't render correct, the icons seems to being sized to fill the complete browser view. The issue occurs in both Firefox and Chrome though they aren't quite as large in Chrome.

In the angular seed this wasn't an issue. px-rangepicker rendered with the icon sizes matching that of its demo page.

Chrome
![px-rangepicker-chrome](https://cloud.githubusercontent.com/assets/1684641/19039086/6ac4ee68-8976-11e6-8fc6-f05b23c6f5ca.png)

Firefox
![px-rangepicker-firefox](https://cloud.githubusercontent.com/assets/1684641/19039087/6ac66d1a-8976-11e6-9295-e0b837ef25d8.png)

Also note the rendering of the nav icons.

**Comment by manderson23** [comment]
For now we can workaround this be adding the following to seed-these.scss
```
// Prevent the nav icons from filling the width of the column.
.nav-item--icon {
  width: 24px;
  height: 24px;
  float: left;
  margin-top: 0.5rem;
}

// Fix size of icons in px-rangepicker
.dtIcon {
  float: left;
}
```

**Comment by mdwragg** [comment]
Hi,

Whoa - cool icons!

I just tried this out in the latest commit on `polymer-seed` and all looks good to me. We've done a world of fixin' up this last week to make it a lot more polished...

Just as an aside, those style changes you made _should_ work for now but will break in a browser with shadow dom turned on by default - this would stop style leakage into web components.

My markup looks like this for the `blankpage-view.html`. I tried it like your example too with just the `px-context-browser` in the template:

```
<link rel="import" href="../../bower_components/polymer/polymer.html">
<link rel="import" href="../../bower_components/px-rangepicker/px-rangepicker.html">
<link rel="import" href="../../bower_components/px-sample-cards/blank-card.html">
<dom-module id="blankpage-view">
  <template>
    <blank-card id="myCard">
      <px-rangepicker></px-rangepicker>
    </blank-card>
  </template>
  <script>
    Polymer({
      is: 'blankpage-view',
      properties: {},
      ready: function() {
        console.log('blankpage-view ready()')
      }
    });
  </script>
</dom-module>
```

**Comment by manderson23** [comment]
Thanks. I'll take a look at pulling in the latest seed changes at some point.

**Comment by mdwragg** [comment]
👍
