### ISSUE TITLE
Polymer-Only: When viewing a child asset, breadcrumb under the selector is incorrect.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/predix-seed#55]
In Polymer seed app, navigate to the child asset/detail view page by selecting the Select Context dropdown and opening the child asset in the context browser.  
Note the breadcrumb on the top left hand corner doesn't reflect the correct view.  It still shows, parent asset not "parent asset > child asset".
Screenshots of angular seed vs. Polymer seed included.

![context_browser_breadcrumb_issue](https://cloud.githubusercontent.com/assets/10835611/19166245/a994824c-8bbb-11e6-99ac-3446d6490a83.png)
![breadcrumb_persistent_onoriginalseed](https://cloud.githubusercontent.com/assets/10835611/19166253/acfb12fc-8bbb-11e6-9d41-629d2d6dc00c.png)

**Comment by gedesigntech** [comment]
Fixed and fix will be available in upcoming release (most likely mid-December)
