### ISSUE TITLE
When viewing a child asset in context browser, dashboard in the nav bar is not functional.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/predix-seed#56]
In Polymer Seed app, navigate to the child asset view in context browser.
Note the dashboard in side nav is not functional. Expected selecting "Dashboards" in side nav would redirect back to the main page and clear the context.  
In contrast, when in child asset view, selecting the blank page option in side nav redirects to blank page as expected. 

The behavior is actually the same in the angular version as well.

**Comment by gedesigntech** [comment]
This seems working as designed.  When navigating to a different node in the context browser, the Dashboards view is still in place.  Hence, when 'selecting' Dashboards in side nav when Child Asset view is active, you are simply selecting what is already active.
