### ISSUE TITLE
Polymer-Seed:  Replace the bar chart in child asset view with time series chart.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/predix-seed#59]
Bar chart deprecation message in browser console log when viewing the child asset/detail view.  Should replace the bar chart example with times series in the near future.

![deprecation_barchart](https://cloud.githubusercontent.com/assets/10835611/19170540/b4edbe1c-8bcd-11e6-87f0-fd3719468fe6.png)

**Comment by gstroup** [comment]
Yes, we plan to remove the px-chart and use px-vis-timeseries.  Thanks!

**Comment by gedesigntech** [comment]
Time series chart and appropriate data source placed;  will be available in upcoming release (most likely mid-December)
