### ISSUE TITLE
post-install hook for bower dependencies

### ISSUE THREAD

**Issue by morficus** [PredixDev/predix-seed#6]
Not everyone has Bower installed on their machine and this can be a barrier to new comers who just want to get the seed application up and running.

This issue is to request the use of [npm-scripts](https://docs.npmjs.com/misc/scripts) to expedite the installation of Bower dependencies while removing the need to have Bower installed globally.

**Comment by nonmetalhail** [comment]
@carlosfhernandez This is a feature request. Can you please prioritize this?

**Comment by mdwragg** [comment]
Bower is a hard dependency on our platform, we won't be implementing this enhancement. Thank you for the suggestion though.

**Comment by morficus** [comment]
Thanks for taking the time to understand the desire behind this request :-1:
