### ISSUE TITLE
Predix-seed: polymer only

### ISSUE THREAD

**Issue by arnaudLC35** [PredixDev/predix-seed#65]
Hi,

In Predix-seed (polymer only and now develop) the dashboard is using bespoke px-deck-index and px-deck which don't seems to have the capability of sharing context between cards which they include or between other cards defined in the dashboards-view compare to px-deck, px-dashboard and px-card defined in px-card.

While moving from the bespoke px-deck-index to px-dashboard it is required to stringify the DeckId.
 From:
 `<px-deck-index
      view-service-base-url="[[viewServiceBaseUrl]]"
      deck-id="[[_selectedDeckId]]">
 </px-deck-index>`
to
`<px-dashboard 
    view-service-base-url="{{viewServiceBaseUrl}}" 
    selected-deck-id="{{_selectedDeckId}}" 
    context="{{context}}">
</px-dashboard>`

however it do not recognize "px.dealer": is it a problem in px-dashboard or the way that predix-seed is set up? Is there explanation to move from the use of those px-deck and px-deck-index to the elements from px-card as defined in the documentation? Or is their a work arround to be able to share context between dashboard-view, px-deck-index and the then created px-deck and associated px-cards?

Thanks

**Comment by gedesigntech** [comment]
Hi @arnaudLC35 it is correct that px-deck and px-deck-index are custom elements that are part of the new Polymer based seed (by the way, it is also the master branch).  As such, these custom elements are only provided as examples, with no guarantees for full functionality and being free from bugs.

Alternatively, you are free use other elements.  For example, you can replace dashboards-view's contents and replace px-deck-index with other components that you know works with context sharing.

**Comment by gedesigntech** [comment]
Closing this issue - will not fix in the Predix UI Seed, but will fix in px-deck and px-deck-index if these become official Predix UI components
