### ISSUE TITLE
How to migrate from angular-seed to polymer-only-seed

### ISSUE THREAD

**Issue by imthinhvu** [PredixDev/predix-seed#66]
Are there step by step instructions on how to migrate a Predix project using the angular-seed to the new polymer-seed? If not, will there be guidance on migrating later on?

**Comment by gedesigntech** [comment]
There are currently no plans to provide instructions on migrating from the previous version of the seed to the new one, as the new code and the provided examples should be sufficient.  We would gladly answer questions on the new version, to further assist.  Thanks
