### ISSUE TITLE
How to link predix time series to a px-vis-timeseries element

### ISSUE THREAD

**Issue by mirekPindjak** [PredixDev/predix-seed#73]
Hi
Is there a plan to update "SERVINTEG.md" with an simple example how to link a predix service such asset or timeseries to polymer elements?
Thank you
Mirek

**Comment by gstroup** [comment]
Yes, we hope to publish some guides on that topic soon.  For now, please look in the branch called microservice-integration.

**Comment by mirekPindjak** [comment]
Hi
Could you be more specific about when you plan to write few lines about the topic? Q1 2017?

It would be highly appreciated If there is anyone (reading this case) who can help me with that before the guide is written.
Thanks
Mirek

**Comment by gstroup** [comment]
Should be published in the next few days.  I'm writing a tutorial now.  In the meantime, we already have similar tutorials here:
https://www.predix.io/resources/tutorials/journey.html#1605
That shows how to call Predix time series from the nodejs-starter app.  If you have specific questions, please post on the predix.io forum.

**Comment by mirekPindjak** [comment]
Hi and happy new year!
Have you got a chance to advance on the tutorial yet?
Thanks 
Mirek

**Comment by gstroup** [comment]
Still working on scripting and finalizing the tutorial.  But for now, you can look at the winddata-view for a basic example.
https://github.com/PredixDev/predix-seed/blob/develop/public/elements/views/winddata-view.html
Hope this helps.

**Comment by gstroup** [comment]
Cleaning up old issues.  This tutorial should answer this question.
https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=2273&tag=2100&journey=Predix%20Web%20App%20Starter&resources=2101,1544,2225,1549,1736,2273
If not please raise an issue on https://github.com/PredixDev/predix-webapp-starter
