### ISSUE TITLE
npm install fails for web-component-tester dependency

### ISSUE THREAD

**Issue by revunurisatish** [PredixDev/predix-seed#74]
Not able to setup seed on local machine, fails in npm install phase giving error for web-component-tester dependency

**Comment by mdwragg** [comment]
Hi,

Installation issues for WCT should be logged against the WCT repo - https://github.com/Polymer/web-component-tester

Thanks.

**Comment by mdwragg** [comment]
Hi,

I've removed WCT from the `devDependencies` for the seed, it is not required locally. WCT is usually installed globally. This should allow you to at least install the seed and its dependencies but wont solve your WCT installation problems overall :-)

CC/ @gedesigntech

**Comment by gstroup** [comment]
`gulp dist` task is failing now, unless you have wct installed globally.  So... should we add note to README explaining that this is required??  Or keep it in the package.json?

**Comment by gstroup** [comment]
actually, looks like we will need to add it back in to package.json.

**Comment by mdwragg** [comment]
WCT shouldn't be ran by `gulp`, it should be installed globally. Apologies I missed that it was in the gulpfile too...

**Comment by mdwragg** [comment]
(well, it _could_ be ran by gulp but for consistency with the rest of Predix UI, probably not ;)
