### ISSUE TITLE
Tutorial (Adding Authentication to the Predix UI Seed) outdated

### ISSUE THREAD

**Issue by cnd5041** [PredixDev/predix-seed#77]
#7245fcd
Commit: 7245fcd3fb07ed2e208f27d4bf07c8126c288465

I think this causes the file to deviate from the tutorial: https://github.com/PredixDev/predix-seed/blob/develop/tutorials/USERAUTH.md

i.e. in the tutorial, it says to go to /secure after entering localConfig values, which does not work. Also, the 'Authenticating All Routes' section is probably different.

**Comment by gstroup** [comment]
Thanks for catching this.  I updated the app, so the /secure route will still work, mainly just for educational purposes.  And I updated the USERAUTH.md file to explain the situation.  Let us know if you see any more problems.
