### ISSUE TITLE
After CF Push - Getting browser error Polymer is not a function

### ISSUE THREAD

**Issue by mirekPindjak** [PredixDev/predix-seed#79]
Hi
I have deployed seed app into cloud (cf push). I have changed only app name, and nothing else.
When I browse the deployed app I get and error: "Polymer is not a function".
Is there something I did wrong?
Deployed app URL:
https://predixlabseed.run.aws-usw02-pr.ice.predix.io

Thanks
Mirek GE

**Comment by gstroup** [comment]
Are you using the latest code?  This was an issue that we fixed 10 days ago.  Please pull the latest code and try again.  Also don't forget to run `gulp dist` before `cf push`

**Comment by mirekPindjak** [comment]
Solved when using the latest code version.
Thank you very much to Greg Stroup
