### ISSUE TITLE
Cannot find module 'gulp-load-plugins'

### ISSUE THREAD

**Issue by prakashdge** [PredixDev/predix-seed#82]
I ran following commands in my local

npm install --global gulp
npm install
gulp
then getting the following error.

Error: Cannot find module 'gulp-load-plugins'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)

**Comment by suman28** [comment]
run the following command:

npm install gulp-load-plugins --save

**Comment by gstroup** [comment]
This module is specified in the package.json.  Must have been a problem during your npm install.
