### ISSUE TITLE
Spacings should be derived from px-spacing-design

### ISSUE THREAD

**Issue by mdwragg** [PredixDev/predix-seed#84]
As per comments in https://github.com/PredixDev/predix-seed/pull/83, all spacing units should be derived from https://www.predix-ui.com/?show=px-spacing-design&type=css.

**Comment by mdwragg** [comment]
(specifically seed-footer.scss)

**Comment by gstroup** [comment]
Moved to new repo:
https://github.com/PredixDev/predix-webapp-starter/issues/7
