### ISSUE TITLE
Detail View: Timeseries resize issue when navigating back to the view.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/predix-seed#88]
1) Navigate to detail view.
2) Use the side nav to navigate to blank page.
3) While on blank page, resize your browser window.
4) Navigate back to the detail view and note the timeseries chart has been resized.
5) Resizing the browser window back to the original size, doesn't fix the issue.

Looks like the height of the card is not adjusting to accommodate proper rendering of the chart.

Screenshot:
![screen shot 2016-12-20 at 10 34 27 am](https://cloud.githubusercontent.com/assets/10835611/21363095/01ab06c6-c6a0-11e6-8d20-f62e005117ca.png)

**Comment by gstroup** [comment]
fixed in new version of predix-webapp-starter.
