### ISSUE TITLE
Getting a 404 on load when the seed app is deployed to the cloud.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/predix-seed#89]
Pre-req: Deploy the seed to the cloud and use Safari 9.1.2.
1) Open the console log and load the seed.
2) Note the 404 error on web-animations-next-min.js.map

Doesn't seem to affect functionality, possibly related to nav-app collapse/expand?
Havent' seen this in other browsers, except Safari 9.1.2.

Screenshot:
![screen shot 2016-12-20 at 10 38 31 am](https://cloud.githubusercontent.com/assets/10835611/21363340/fb26242e-c6a0-11e6-85b7-36530f096a01.png)

**Comment by gstroup** [comment]
fixed in predix-webapp-starter
