### ISSUE TITLE
NS_Error_Failure when resizing the detail view in Firefox.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/predix-seed#90]
1) Navigate to the Detail View on the seed.
2) Resize the browser window.
3) Note the error in console log coming from px-simple-chart-common-behavior.js

Seen in Firefox, version 50.0.1.

Screenshot:

![screen shot 2016-12-20 at 10 44 49 am](https://cloud.githubusercontent.com/assets/10835611/21363529/cea57854-c6a1-11e6-8cfc-f638c963d438.png)

**Comment by gstroup** [comment]
fixed in predix-webapp-starter
https://github.com/PredixDev/predix-webapp-starter
