### ISSUE TITLE
Missing icons and context browser down arrows in the cloud deployed version of the seed app.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/predix-seed#91]
Latest version of the seed deployed to the cloud: https://predixuiseed.run.aws-usw02-pr.ice.predix.io/#/dashboards is missing the icons in the nav bar and the arrows in the context browser/dropdown.
No 404 errors in console log. Possibly a caching issue?
Was able to reproduce on all browsers on the mac with cache disabled.

Screenshot:

![screen shot 2016-12-20 at 8 50 12 am](https://cloud.githubusercontent.com/assets/10835611/21365851/196ca1f0-c6ac-11e6-854a-e57b5cf85f55.png)

**Comment by gstroup** [comment]
fixed in web-app-starter
