### ISSUE TITLE
Using iron-ajax to load timeseries chart data from sample data doesn't render the chart in IE11.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/predix-seed#92]
Uncommented the iron-ajax statement in winddata-view.html file to enable adding a third nav option in the app-nav and loading timeseries data from sample json data in server/time-series/delta-egt.

I was able to get that the chart to render data in FF, Chrome and Safari; however, win8.1+IE11 and win7+IE11 don't render at all.  There are no errors in their console log either.

Screenshots:

In Firefox:

![screen shot 2016-12-20 at 4 41 27 pm](https://cloud.githubusercontent.com/assets/10835611/21373367/3ace0c68-c6d3-11e6-9a91-241f1f31fde9.png)

In win8.1+IE11(VM) & Win7+IE11(HW):

<img width="1274" alt="screen shot 2016-12-20 at 4 42 32 pm" src="https://cloud.githubusercontent.com/assets/10835611/21373385/5e63b6c8-c6d3-11e6-8df6-39185501b152.png">

**Comment by gstroup** [comment]
removed from new version of predix-webapp-starter.
