### ISSUE TITLE
Footer Rendering issue in IE11 with local instance of seed.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/predix-seed#93]
This issue only occurs if the seed app is not deployed to the cloud.  When pointing the browser to a local instance, the footer sometimes doesn't render in IE11 (Win7+IE11) at all and sometimes(win8.1+IE11), it renders with none of the text elements.  If the seed is deployed to the cloud and you use IE11 to view it, the footer is present.

See Screenshots:

Win8.1+IE11 (VM):

<img width="1276" alt="screen shot 2016-12-20 at 4 47 20 pm" src="https://cloud.githubusercontent.com/assets/10835611/21373497/48375462-c6d4-11e6-9f81-76886ee321aa.png">

Win7+IE11 (HW)

![2016-12-20_1653](https://cloud.githubusercontent.com/assets/10835611/21373643/60d3b866-c6d5-11e6-8258-e7a0eff864d6.png)

**Comment by gstroup** [comment]
Closing.  New issue is here:
https://github.com/PredixDev/predix-webapp-starter/issues/1
